name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    strategy:
      matrix:
        python-version: [ "3.12" ]
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: django_password
          POSTGRES_DB: django_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run image
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: 1.8.4
    - name: Install dependencies
      run: poetry install
    - name: Testing
      env:
        POSTGRES_USER: django_user
        POSTGRES_PASSWORD: django_password
        POSTGRES_DB: django_db
        POSTGRES_HOST: 127.0.0.1
        POSTGRES_PORT: 5432
        ACCESS_TOKEN: qwerty123456
      run: |
        poetry run flake8 src/
        poetry run pytest


  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: tests

    steps:
    - name: Send deploy request
      run: |
        curl -L -H "${{ secrets.SERVER_DEPLOY_TOKEN }}" "http://${{ secrets.SERVER_WEBHOOK_URL }}?repo=family_finances_2"
